[2025-09-08T15:35:21.634+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-08T15:35:21.640+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.update_values manual__2025-09-08T15:35:10.997528+00:00 [queued]>
[2025-09-08T15:35:21.646+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.update_values manual__2025-09-08T15:35:10.997528+00:00 [queued]>
[2025-09-08T15:35:21.646+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-09-08T15:35:21.657+0000] {taskinstance.py:2888} INFO - Executing <Task(SqliteOperator): update_values> on 2025-09-08 15:35:10.997528+00:00
[2025-09-08T15:35:21.660+0000] {standard_task_runner.py:72} INFO - Started process 17794 to run task
[2025-09-08T15:35:21.663+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sql_pipeline', 'update_values', 'manual__2025-09-08T15:35:10.997528+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/executing_sql_pipeline.py', '--cfg-path', '/tmp/tmpviqx0rjg']
[2025-09-08T15:35:21.664+0000] {standard_task_runner.py:105} INFO - Job 73: Subtask update_values
[2025-09-08T15:35:21.691+0000] {task_command.py:467} INFO - Running <TaskInstance: executing_sql_pipeline.update_values manual__2025-09-08T15:35:10.997528+00:00 [running]> on host codespaces-9bd7b3
[2025-09-08T15:35:21.735+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='loonycorn' AIRFLOW_CTX_DAG_ID='executing_sql_pipeline' AIRFLOW_CTX_TASK_ID='update_values' AIRFLOW_CTX_EXECUTION_DATE='2025-09-08T15:35:10.997528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-08T15:35:10.997528+00:00'
[2025-09-08T15:35:21.736+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-08T15:35:21.749+0000] {sql.py:266} INFO - Executing: 
            UPDATE users SET city = 'Seattle';
        
[2025-09-08T15:35:21.752+0000] {base.py:84} INFO - Retrieving connection 'my_sqlite_conn'
[2025-09-08T15:35:21.776+0000] {base.py:84} INFO - Retrieving connection 'my_sqlite_conn'
[2025-09-08T15:35:21.776+0000] {sql.py:509} INFO - Running statement: 
            UPDATE users SET city = 'Seattle';
        , parameters: None
[2025-09-08T15:35:21.777+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: no such column: city
[2025-09-08T15:35:21.781+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=executing_sql_pipeline, task_id=update_values, run_id=manual__2025-09-08T15:35:10.997528+00:00, execution_date=20250908T153510, start_date=20250908T153521, end_date=20250908T153521
[2025-09-08T15:35:21.791+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-08T15:35:21.792+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 73 for task update_values (no such column: city; 17794)
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: no such column: city
[2025-09-08T15:35:21.839+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-08T15:35:21.847+0000] {logging_mixin.py:190} WARNING - /usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class SqliteOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2025-09-08T15:35:21.854+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-08T15:35:21.860+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
